Repository Consensys/linea-specification, pull requests merged in 2025-03, with the labels that each got.

#99 feat: `CN = 0 <=> TX_EXEC = 0` enforced by explicit constraint
  hub/generalities/context/numbers.tex
Labels: bug

#96 Context consistency argument fix to accommodate for iso-`HUB_STAMP` read and update
  hub/consistencies/context/permutation.tex
  hub/consistencies/environment/columns.tex
  hub/context/_inputs.tex
  hub/context/specialized_constraints.tex
  hub/generalities/context/numbers.tex
  hub/instruction_handling/account/constraints.tex
  hub/instruction_handling/call/generalities/lua/entry.lua.tex
  hub/instruction_handling/call/precompiles/modexp/failure_KTR.tex
  hub/instruction_handling/call/precompiles/modexp/success.tex
  hub/instruction_handling/copy/specifics/codecopy.tex
  hub/instruction_handling/copy/specifics/extcodecopy.tex
  hub/instruction_handling/copy/specifics/returndatacopy.tex
  hub/instruction_handling/create/generalities/_inputs.tex
  hub/instruction_handling/create/generalities/final_context_row.tex
  hub/instruction_handling/halt/return/generalities.tex
  hub/instruction_handling/halt/revert/constraints.tex
  hub/instruction_handling/logs/constraints.tex
  hub/instruction_handling/storage/constraints.tex
  notes/contexts.md
Labels: bug

#106 feat: TRM redesign
  .github/workflows/compile.yml
  pkg/trm.sty
  trm/.DS_Store
  trm/_all_trm.tex
  trm/_inputs.tex
  trm/_local.tex
  trm/binary.tex
  trm/byteDec.tex
  trm/columns.tex
  trm/constancies.tex
  trm/heartbeat.tex
  trm/introduction.tex
  trm/lookup.tex
  trm/plateau.tex
  trm/setting_wcp_arg.tex
  trm/target.tex
Labels: London to Pectra

#103 Arithmetization of `MXP` redesign
  Makefile
  mxp_v3/_all_mxp_v3.tex
  mxp_v3/_inputs.tex
  mxp_v3/_local.tex
  mxp_v3/columns/_inputs.tex
  mxp_v3/columns/common.tex
  mxp_v3/columns/computation/_inputs.tex
  mxp_v3/columns/computation/calls.tex
  mxp_v3/columns/computation/columns.tex
  mxp_v3/columns/decoder.tex
  mxp_v3/columns/macro.tex
  mxp_v3/columns/scenario/_inputs.tex
  mxp_v3/columns/scenario/columns.tex
  mxp_v3/columns/scenario/shorthands.tex
  mxp_v3/computations/_inputs.tex
  mxp_v3/computations/generalities.tex
  mxp_v3/computations/intro.tex
  mxp_v3/computations/msize.tex
  mxp_v3/computations/mxpx.tex
  mxp_v3/computations/non_msize.tex
  mxp_v3/computations/non_msize_non_trivial.tex
  mxp_v3/computations/state_update.tex
  mxp_v3/computations/state_update_byte_pricing.tex
  mxp_v3/computations/state_update_word_pricing.tex
  mxp_v3/computations/trivial.tex
  mxp_v3/consistency/_inputs.tex
  mxp_v3/consistency/columns.tex
  mxp_v3/consistency/constraints.tex
  mxp_v3/consistency/intro.tex
  mxp_v3/consistency/permutation.tex
  mxp_v3/design_document.md
  mxp_v3/generalities/_inputs.tex
  mxp_v3/generalities/binarities.tex
  mxp_v3/generalities/constancies.tex
  mxp_v3/generalities/heartbeat.tex
  mxp_v3/generalities/perspectives/_inputs.tex
  mxp_v3/generalities/perspectives/computation.tex
  mxp_v3/generalities/perspectives/decoder.tex
  mxp_v3/generalities/shorthands.tex
  mxp_v3/generalities/transition_graph.tex
  mxp_v3/hub_mxp_interface.tex
  mxp_v3/instruction_decoder_representation.tex
  mxp_v3/intro.tex
  mxp_v3/lookups/_inputs.tex
  mxp_v3/lookups/mxp_into_euc.tex
  mxp_v3/lookups/mxp_into_instruction_decoder.tex
  mxp_v3/lookups/mxp_into_wcp.tex
  mxp_v3/lua/_todo.md
  mxp_v3/lua/decision_tree.lua.tex
  mxp_v3/lua/decoder.lua.tex
  mxp_v3/lua/hub_mxp_interface.lua.tex
  mxp_v3/lua/msize.lua.tex
  mxp_v3/lua/mxpx.lua.tex
  mxp_v3/lua/state_update.lua.tex
  mxp_v3/lua/state_update_byte_pricing.lua.tex
  mxp_v3/lua/state_update_word_pricing.lua.tex
  mxp_v3/lua/trivial.lua.tex
  pkg/common.sty
  pkg/expansion.sty
  pkg/xkeyval_macros/euc_calls.sty
Labels: enhancement, London to Prague, arithmetization

#135 EIP-1153 Arithmetization: Transient storage opcodes
  _notes/EIP-1153-transient-storage-opcodes.md
  hub/_all_hub.tex
  hub/columns/_inputs.tex
  hub/columns/shared.tex
  hub/columns/stack.tex
  hub/columns/transient.tex
  hub/consistencies/_inputs.tex
  hub/consistencies/_local.tex
  hub/consistencies/transient/_inputs.tex
  hub/consistencies/transient/columns.tex
  hub/consistencies/transient/constraints.tex
  hub/consistencies/transient/first_again.tex
  hub/consistencies/transient/permutation.tex
  hub/heartbeat/peeking_flags.tex
  hub/instruction_handling/storage/_inputs.tex
  hub/instruction_handling/storage/constraints.tex
  hub/instruction_handling/transient/_inputs.tex
  hub/instruction_handling/transient/_local.tex
  hub/instruction_handling/transient/constraints.tex
  hub/instruction_handling/transient/flags.tex
  hub/instruction_handling/transient/shorthands.tex
  hub/transient/_inputs.tex
  hub/transient/specialized/_inputs.tex
  hub/transient/specialized/reading.tex
  hub/transient/specialized/same_slot.tex
  hub/transient/specialized/undoing.tex
  pkg/column_generator.py
  pkg/common.sty
  pkg/env.sty
  pkg/flags_stamps_selectors.sty
  pkg/xkeyval_macros/transient.sty
Labels: London to Prague, arithmetization
